# The app's runtime configuration.

application: trac-us
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on

handlers:

- url: /static
  static_dir: static

