application: trac-us
version: 1
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 10

libraries:
- name: MySQLdb
  version: "latest"

- name: ssl
  version: "latest"

- name: pycrypto
  version: "2.6"

- name: yaml
  version: "latest"

- name: PIL
  version: "latest"

builtins:
- remote_api: on
- appstats: on

inbound_services:
- warmup

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /api/updates/.*
  script: main.application
  secure: optional

- url: /.*
  script: main.application
  secure: always

skip_files:
- local
- venv
- requirements
- .git
- ^(.*/)?.*\.py[co]$
