# The app's runtime configuration.

application: trac-us
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.5"

- name: MySQLdb
  version: "latest"

- name: ssl
  version: "latest"

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /api/updates/.*
  script: main.application
  secure: optional

- url: /.*
  script: main.application
  secure: always

skip_files:
- local

