# The app's runtime configuration.

application: trac-us
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.5"

- name: MySQLdb
  version: "latest"

#env_variables:
#  DJANGO_SETTINGS_MODULE: 'settings.common'

#builtins:
#- django_wsgi: on


handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py

# TODO: set sensitive pages to use https
#- url: /users
#  script: google.appengine.ext.django.main.app
#  secure: always
#- url: /.*
#  script: google.appengine.ext.django.main.app
